### ISSUE TITLE
Update for compatibility with UMM 0.31.0.0

### ISSUE THREAD

**Issue by LilithL** [Banjobeni/DVDispatcherMod#3]
Hi, is it possible to update the .NET version from 4.6 to 4.8 ?

I tried a quick and dirty build on my setup by directly tweaking DVDispatcherMod.csproj to use the same .NET as UMM 0.31.0.0.
Tested the mod on DV with update B99 and it seems to work.

In any case, thanks for your work on this mod !

**Comment by Banjobeni** [comment]
Hi, yeah, I'll give it a shot with the next update. Might be a while though, I'm currently working on PersistentJobs when I have time.
