### ISSUE TITLE
Request not clear other notifications

### ISSUE THREAD

**Issue by Nightwind416** [Banjobeni/DVDispatcherMod#4]
I just created a Twitch Chat mod (https://www.nexusmods.com/derailvalley/mods/1069) that happens to use the same in-game notification system. I noticed that my chat messages were being cleared very quickly, but only when a Job was being looked at/held and displaying your notification.

Are you able to adjust so your notifications to not clear others?

**Comment by Banjobeni** [comment]
Hi Nightwind. Thanks for raising a compatibility issue with DVDispatcher.

Interaction with the (non-VR) popup notification is implemented in [DispatcherHintShower](https://github.com/Banjobeni/DVDispatcherMod/blob/master/DVDispatcherMod/DispatcherHintShowers/DispatcherHintShower.cs). I see there is clearExisting flag in NotificationManager.ShowNotification() that I don't set so it's true by default, this could be changed I guess. But I think for this to be handled correctly there would need to be a priority system for notification, and I don't see anything related to that in the base game.

I suggest you take DVDispatcher and try to modify it such that it plays more nicely with your notifications and test that. If you're happy with the result I'm happy to discuss a PR or you can reach me on discord.

**Comment by Nightwind416** [comment]
Thanks for replying. I agree a priority system would be better handled, but I am very amateur to all this and entirely self taught, and almost exclusively with Python. I think the small pull request I made should be all that is needed. It seemed to be working fine when I tested on my setup.

It looks like there is a "private int GetIndex(GameObject notification)" in the DV.UIFramework dll, but this is where I start to fail on following the code and if it could be implemented as a priority system. If concerned about priority for now, would you be able to add the "clearExisting: false" flag as a toggle option in the settings for Dispatcher?

**Comment by Banjobeni** [comment]
Okay, that's sufficient info for me now - you've confirmed that your usecase works with the clearExisting flag set to false. I've merged your pull request.

Thanks for taking part in this.
